version: '3'
services:
  backend:
    volumes:
      - ./backend:/app/backend
    container_name: backend
    build: ./backend
    command: ./gradlew bootRun
    # tty: true # デバッグ用にターミナルを有効化
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/attendance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    volumes:
      - ./frontend:/app/frontend
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: attendance_db
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # my.cnfファイルをマウント
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
