# version: '3'
services:
  backend:
    volumes:
      - .:/workspace:cached
    container_name: backend
    build: ./backend
    # tty: true # デバッグ用にターミナルを有効化
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/attendance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    volumes:
      - .:/workspace:cached
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: attendance_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
